# # version: '3.8'

# # services:
# #   backend:
# #     build:
# #       context: ./blog_project
# #       dockerfile: Dockerfile
# #     ports:
# #       - "8000:8000"
# #     volumes:
# #       - ./blog_project:/app
# #     environment:
# #       - DEBUG=True
# #     command: python manage.py runserver 0.0.0.0:8000

# #   frontend:
# #     build:
# #       context: ./frontend  
# #       dockerfile: Dockerfile 
# #     ports:
# #       - "5173:80"
# #     volumes:
# #       - ./frontend:/app
# #       - /app/node_modules
# #     depends_on:
# #       - backend


# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#     ports:
#       - "5432:5432"

#   backend:
#     build:
#       context: ./blog_project
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./blog_project:/app
#     environment:
#       - DEBUG=True
#     command: >
#       sh -c "python manage.py migrate &&
#              python manage.py runserver 0.0.0.0:8000"
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "5173:80"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     depends_on:
#       - backend

# volumes:
#   postgres_data:


version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./blog_project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./blog_project:/app
    environment:
      - DEBUG=True
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: ./blog_project
      dockerfile: Dockerfile
    volumes:
      - ./blog_project:/app
    command: celery -A blog_project worker --loglevel=info
    depends_on:
      - db
      - redis
      - backend

  celery-beat:
    build:
      context: ./blog_project
      dockerfile: Dockerfile
    volumes:
      - ./blog_project:/app
    command: celery -A blog_project beat --loglevel=info
    depends_on:
      - db
      - redis
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: