version: '3.8'

services:
  backend:
    build:
      context: ./blog_project
    container_name: blog_backend
    volumes:
      - ./blog_project:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: blog_frontend
    volumes:
      - ./frontend/src:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: blog_db
    volumes:
      - blog_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"

volumes:
  blog_db_data:
